---
- hosts: localhost 
  vars:
    oauth_token: "{{ lookup('env', 'DO_OAUTH') }}"
  tasks:
  - name: Get DO droplet data
    uri:
      url: "https://api.digitalocean.com/v2/droplets"
      method: GET
      headers:
        Authorization: "Bearer {{ oauth_token }}"
      return_content: yes
    register: droplets

  - name: DEBUG droplets
    debug: var=droplets.json
